### ISSUE TITLE
Using arrays

### ISSUE THREAD

**Issue by TheCowMonarch** [ZengineeringTeam/ResearchTable#10]
Is there an easy way to set an entire arrays worth of items to be used to the items required to advance to the next age? 

example array
var stage2ItemAdvancement as IIngredient[] = [
  (<ore:leather>),
  (<ore:plankWood>),
  (<ore:cobblestone>),
  (<minecraft:melon>),
  (<ore:fiberHemp>),
  (<minecraft:brick_block>)
];

.addCondition( stage2ItemAdvancement * 1024 )

**Comment by Snownee** [comment]
Done. https://minecraft.curseforge.com/projects/research-table/files/2703830

Just a bit different to what you imagined. But it is easy to understand.
