### ISSUE TITLE
Suggestion: Hide research from showing up until criteria met

### ISSUE THREAD

**Issue by Streamcyper** [ZengineeringTeam/ResearchTable#11]
I don't know if this is already a feature, but I would love it it was possible to set a "hidden if / unless " criteria. So that if the research will only be show up in the table if you meet them, I know I can stop people from researching it but would like to be able to hide it from view until they I want them to be able to see it. 

If it has already been asked for/considered sorry for wasting your time, and if it has been added could you please add a description in the example showing this?

**Comment by Snownee** [comment]
There is an option to let research shows only if the research has all of required stages. You can toggle that in config file. Does that satisfy your need?

**Comment by Streamcyper** [comment]
If that is the case then that is exactly what I needed. Not sure how I managed to miss that option. Thank you very much!
