### ISSUE TITLE
Fake error on load?

### ISSUE THREAD

**Issue by DraxxisGH** [ZengineeringTeam/ResearchTable#12]
When my pack loads it throws up errors with the words I have here, for example "ResearchTable.builder("iron", X)
  .setTitle("Tools+")
  .setIcons(<minecraft:iron_ingot>)
  .setDescription("Access to iron")
  .addCondition(<minecraft:cobblestone> * 250)
  .addCondition(<minecraft:log> * 100)
  .setRewardStages("iron")
  .build();"

Where the X is is what it says is wrong, but if I remove the X it throws errors in CT, what's up with that?

**Comment by Snownee** [comment]
Have you seen this: https://github.com/ZengineeringTeam/ResearchTable/blob/master/run/scripts/test.zs#L5-L7

Does this pass the compilation?

**Comment by DraxxisGH** [comment]
Oh wait I'm stupid

**Comment by DraxxisGH** [comment]
![image](https://user-images.githubusercontent.com/38152067/57725667-ae4e9d80-765b-11e9-909f-0d26b0bae058.png)

Throws that error for everything

`ResearchTable.builder("conveyors3")`
.setTitle("Conveyor Upgrade `3")`
`.setIcons(<logisticalautomation:conveyor_express>)`
.setDescription("An upgrade in speed to the Fast `conveyor")`
.addCondition(<logisticalautomation:conveyor_fast> * `250)`
.addCondition(<immersiveengineering:metal:39> * `1500)`
`.setRewardStages("conveyors3")`
`.build();`

**Comment by Snownee** [comment]
I am sure that you should learn ZenScript from the beginning again..

```
var cat = ResearchTable.addCategory(<minecraft:grass>);

ResearchTable.builder("conveyors3", cat)
.setTitle("Conveyor Upgrade 3")
.setIcons(<logisticalautomation:conveyor_express>)
.setDescription("An upgrade in speed to the Fast conveyor")
.addCondition(<logisticalautomation:conveyor_fast> * 250)
.addCondition(<immersiveengineering:bla:39> * 1500)
.setRewardStages("conveyors3")
.build();
```

**Comment by DraxxisGH** [comment]
(This shouldn't reopen the issue cause I understand now) But to answer, yes I'm pretty new to zenscript myself so I'm still learning.
