### ISSUE TITLE
[Suggestion] - Make items insertable by hand

### ISSUE THREAD

**Issue by BasieBrinkie** [ZengineeringTeam/ResearchTable#14]
Currently, I believe items can only be piped in by hoppers or other transfer mechanisms. If one only wants to use a few items as a condition for the research, that adds unnecessary trouble to insert an item to complete the condition.
My suggestion would make items right-clickable so it is insertable but only if these items are required for the research. Otherwise, you could add a slot in the research table that can consume the item a bit like how the transmutation table from Project E is.

Have a good day!
BasieBrinkie

**Comment by Snownee** [comment]
Actually you can click the "submit" button or insert fluids by hand.

Would that helps you?

**Comment by BasieBrinkie** [comment]
Must have missed that thanks for the reply!
