### ISSUE TITLE
[Suggestion] - Minimum completed stages to unlock research

### ISSUE THREAD

**Issue by BasieBrinkie** [ZengineeringTeam/ResearchTable#15]
Me again, 
It might be nifty to create an option to make a list of possible gamestages that will qualify for the research but only a few is enough to actually do the research. For instance, have the current 
`.setRequiredStages("thisOneIsAlwaysRequiredNoMatterWhat")` and a array with optional gamestages
`.setOptionalStages("one", "two", "three").minimumRequired(2)`
so if you have the required stage and "one' and "three" the research can be done.

BasieBrinkie

**Comment by Snownee** [comment]
Added in 0.7
