### ISSUE TITLE
[Bug] - Can't complete research without conditions

### ISSUE THREAD

**Issue by BasieBrinkie** [ZengineeringTeam/ResearchTable#16]
The code below shows at first research and after you click that it displays complete. Yet if you provide no `.addCondition() ` the complete button doesn't work

> var category = ResearchTable.addCategory(<props:props:343>);    
> ResearchTable.builder("researchKitchenSink", category)
>   .setIcons(<props:props:343>)
>   .setTitle("Unlock All Research")
>   .setDescription("Unlock All Research")
>   .setRequiredStages("gamemodekitchensink")
>   .setRewardStages("one", "two", "three")
>   .setMaxCount(1)
>   .build();

**Comment by Snownee** [comment]
Fixed in 0.7
