### ISSUE TITLE
[Sugestion]: Timed researches

### ISSUE THREAD

**Issue by ThePennitentOne** [ZengineeringTeam/ResearchTable#2]
I would like to suggest adding an option to specify how much time after supplying the required materials is necessary to complete the research. (i also think that on servers the time should count down even when the player who started the research is not online)

**Comment by Snownee** [comment]
Sorry, I can't see the point. I think consuming time should be the producing machine's mission. The goal of Research Table is letting player concentrate on designing supplying line, but not stay idle for materials (or new things).

**Comment by ThePennitentOne** [comment]
I thought about it and you're right. I think requiring complicated items in late-game researches should be enough and then the time required will be dependent on the players automation setup
