### ISSUE TITLE
How can i create an addon for this mod?

### ISSUE THREAD

**Issue by matyklug18** [ZengineeringTeam/ResearchTable#20]
as the name says, i wanna create addon, that would implement more compat. How the API of this mod works?

**Comment by Snownee** [comment]
https://github.com/ZengineeringTeam/ResearchTable/tree/master/src/main/java/snownee/researchtable/plugin

Just see the implement of GameStages or Reskillable. Feel free to ask if you have any problem!

**Comment by matyklug18** [comment]
is it possible to implement mana?

**Comment by Snownee** [comment]
From Botania?

**Comment by matyklug18** [comment]
yes.

**Comment by Snownee** [comment]
I just checked the implement of mana pool. Botania is using interface rather than capability, which means you have to add another block to agent mana

**Comment by matyklug18** [comment]
can i fork this mod and make changes for more support?

**Comment by Snownee** [comment]
Yes but I do not recommend you to do so

**Comment by matyklug18** [comment]
why?

**Comment by Snownee** [comment]
I hope there is only one standard and all users can receive future updates

**Comment by matyklug18** [comment]
ok. i already implemented botania mana support, can i make a pull request(if i can figure out how)?

**Comment by Snownee** [comment]
Yes but please test without Botania installed before pull request
