### ISSUE TITLE
Table fails to register # of fluid containers submitted

### ISSUE THREAD

**Issue by pyure** [ZengineeringTeam/ResearchTable#24]
If you right click an itemstack of 1000mb fluid containers to fulfill a research requirement, the full stack of containers (regardless of # actually required) are consumed but only 1000mb registers towards completion of the requirement.

Tested with: 
* GT-CE Cells
* Forestry containers

**ResearchTable-0.9.0.jar**

**Comment by Snownee** [comment]
Thanks for reporting! I have fixed all bugs
