### ISSUE TITLE
[Suggestion] Research Tables function like Ender Chests

### ISSUE THREAD

**Issue by Seraphaestus** [ZengineeringTeam/ResearchTable#25]
With a really large research task which requires a lot of items, it could take a very long time to transfer items in. My suggestion is to make it so that Research Tables work the same as Ender Chests- you pipe X of an item into Research Table A, and Y of the same item into Research Table B, and if placed by the same user, the task has progressed by X+Y items.
This is how the research mechanic works in Factorio, which allows the user to create massive automation lines feeding into the researchers, with no upper limit on transfer rate.

**Comment by Snownee** [comment]
Thanks for your suggestion. I have think about this before, however:

1. This is irrelevant to theme. If you need to transfer resources from a long distance, just use Ender Chests. Now there are many storage network mods will make this feature aimless.

2. This requires a huge refactor of this project and cause incompatibility with previous versions.

**Comment by Seraphaestus** [comment]
You're misunderstanding why I want the feature, not because of long-distance transfer, but for decreasing research time through being able to create parallel tables and have conveyor lines of resources coming into all of them, instead of being bottlenecked by the six single faces.

I understand if it would be too hard to implement, though you could implement it as a new variant of the research table that exist alongside it or replaces it with a config option, to avoid compat issues.

**Comment by Snownee** [comment]
I will consider that. Thank you!
