### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by brachy84** [ZengineeringTeam/ResearchTable#26]
Pls add categories so it looks much cleaner.

**Comment by vizthex123** [comment]
I support this!

I'd personally rather have a research tree as the UI though, but at least categories would be nice.

**Comment by Snownee** [comment]
added in 1.0

**Comment by brachy84** [comment]
After 1 and a half year I don't need it anymore but nice

**Comment by Snownee** [comment]
lol

**Comment by vizthex123** [comment]
> added in 1.0

nice, thanks
