### ISSUE TITLE
[建议]自动研究

### ISSUE THREAD

**Issue by dong031001** [ZengineeringTeam/ResearchTable#29]
若 #28 实现，则玩家可能需要重复研究同一个研究，那么就需要一个能够使研究台自动化的方案，这里给出的是使用红石信号，您也可以选择其他方式实现。

**Comment by Snownee** [comment]
完成之后如果玩家不在线怎么奖励？

**Comment by dong031001** [comment]
> 完成之后如果玩家不在线怎么奖励？

可以考虑缓存在存档capabilities内监听onPlayerLogIn事件后给予？

**Comment by Snownee** [comment]
比如一个研究在开始时会减去玩家的5级经验，如何保证玩家不在线时能成功减去？

**Comment by dong031001** [comment]
> 比如一个研究在开始时会减去玩家的5级经验，如何保证玩家不在线时能成功减去？

可以将Reward类对象转成nbt存在存档里待玩家下一次进入游戏触发

**Comment by Snownee** [comment]
每次开始研究减5级，你怎么知道离线玩家还有5级可以给你减

**Comment by dong031001** [comment]
> 每次开始研究减5级，你怎么知道离线玩家还有5级可以给你减

那即使玩家在线，怎么知道玩家还有五级可以减呢

**Comment by Snownee** [comment]
Condition

**Comment by dong031001** [comment]
> Condition

明白了，那如果condition更遵从与玩家的话，可能确实自动化难以实现

**Comment by Snownee** [comment]
如果谁想尝试实现一下的话，我已经在今天的更新里提供了基本支持
