### ISSUE TITLE
服务端设置问题

### ISSUE THREAD

**Issue by alkkhsl** [ZengineeringTeam/ResearchTable#32]
在This-Is-My-World-IV-Trial-of-God-v1.2.17 整合包中，使用同版本号的forge开服（未使用插件），出现研究台“研究”按钮点了没反应的情况，单机正常。请问是服务端需要额外配置吗？

**Comment by Snownee** [comment]
不需要

**Comment by alkkhsl** [comment]
> 不需要

顺便问一下，那出现这种情况可能是什么原因呢？尘鸽子没回应，实在是想和小伙伴一起玩这个。

**Comment by Snownee** [comment]
不清楚，无法复现此现象。你用的是什么服务端？

**Comment by alkkhsl** [comment]
> 不清楚，无法复现此现象。你用的是什么服务端？

forge官服

**Comment by alkkhsl** [comment]
因为整合包没有提供服务端，将下载好的客户端所有内容拷贝入forge官服开服，其余都正常。只有研究台点击研究没反应，无法开始。

**Comment by alkkhsl** [comment]
![QQ图片20200206171111](https://user-images.githubusercontent.com/40649667/73922290-daa1fc80-4903-11ea-8896-8d8679650851.jpg)

咨询了几个开过这个服务器的腐竹，都反应有这个问题，应该是模组问题。。有解决办法吗

**Comment by Snownee** [comment]
不知道……没人跟我反映过

**Comment by alkkhsl** [comment]
> 不知道……没人跟我反映过

：）。我现在反映下~这个mod还更新吗？有可能解决吗？

**Comment by alkkhsl** [comment]
Ps：如果是mod原因倒是这么优秀的mod只适配单机，不适配服务器也太可惜了~~=。=

**Comment by Snownee** [comment]
有时间会尝试修复

**Comment by alkkhsl** [comment]
> 有时间会尝试修复

谢谢~打扰啦。

**Comment by alkkhsl** [comment]
已经解决，将整合包mod版本更新到0.9.5正常可用，谢谢！
