### ISSUE TITLE
[Question] sharing progress with others

### ISSUE THREAD

**Issue by Liiw** [ZengineeringTeam/ResearchTable#37]
Hello! Is it possible to sync research progress with another player and also access their research table? If so, how could that be done?

**Comment by Snownee** [comment]
Not possible currently

**Comment by vizthex123** [comment]
Would be nice if things auto-synced though.

**Comment by Liiw** [comment]
True, perhaps it could be made compatible with the mod "Together Forever"?

**Comment by vizthex123** [comment]
[Yeah that mod sounds cool](https://www.curseforge.com/minecraft/mc-mods/together-forever)

Hope the dev can do it.

**Comment by Snownee** [comment]
Hello, I have uploaded a test version with TogetherForever support on my Discord. Any test will be appreciated:

https://discordapp.com/channels/252384449042317313/521399054391967749/771333629988962315

**Comment by vizthex123** [comment]
Can you post it here or post the server invite or something? Can't use that link since I'm not in the server.

**Comment by Snownee** [comment]
https://discord.gg/KzGQW7a

**Comment by vizthex123** [comment]
Thanks! Could you also see if you'd be able to the teams added by FTB Library (might be FTB Teams now?) for sharing? Would be much easier since that's installed alongside FTB quests (and the packs I've found using this mod are quest-based)
