### ISSUE TITLE
research locked behind research

### ISSUE THREAD

**Issue by TheNimbleNinja** [ZengineeringTeam/ResearchTable#4]
hi i was going to use your mod but then i found out i cant lock research behind each other. this would be a great feature to add to the mod as it would make it a true research mod as many mods that have research lock there research behind other research.

**Comment by Snownee** [comment]
You can't lock a research behind another research but you can lock behind stage by using setRequiredStages("stage1", "stage2")

See the [example](https://github.com/ZengineeringTeam/ResearchTable/blob/master/run/scripts/test.zs)

**Comment by Snownee** [comment]
Added in 0.4.3
