### ISSUE TITLE
似乎不支持多人

### ISSUE THREAD

**Issue by ghost** [ZengineeringTeam/ResearchTable#40]
当在服务器游玩时，组队玩家无法同时拥有同等进度。（只能再次提交一次任务）

**Comment by Snownee** [comment]
目前暂不支持。你用的是什么组队模组？

**Comment by ghost** [comment]
游玩的是整合包，整合包内要使用（ResearchTable）来解锁（Game Stages）的阶段物品。
（
    ResearchTable 似乎只能所属玩家才能打开，并提交物品来解锁相应阶段；
    而跟该玩家在一起游玩的话 {似乎不能同步获得该进度}，需要另行在做一个研究台，并且需要再次提交物品来解锁相应阶段。
）
另外该整合包内有 (Better Questing)该模组。

**Comment by ghost** [comment]
期望 ResearchTable 后期能添加多人组队系统；如果那样，那 ResearchTable 将会是一个非常不错的任务系统。

**Comment by Snownee** [comment]
Duplicate of #37
