### ISSUE TITLE
Can't use /tellraw as the completion message

### ISSUE THREAD

**Issue by vizthex123** [ZengineeringTeam/ResearchTable#41]
* Minecraft Version: 1.12.2
 * Mod Version: 0.9.5

I can't figure out how to use the `/tellraw` command in my research.

It's kind of annoying, as I don't want the @ sign that `/say` generates. Not a huge deal though.

Loving the mod btw, it's exactly what I was looking for.

Here's the script:
```
var stone = ResearchTable.addCategory(<minecraft:stone_pickaxe>);

ResearchTable.builder("stone_age", stone)
  .setIcons(<minecraft:stone_pickaxe>)
  .setTitle("Stone Age")
  .setDescription("Research how to use Stone Tools")
  .addCondition(<ore:cobblestone> * 16)
  .setRewardStages("stone_age")
  .setRewardCommands("/tellraw @p {"text":"You've figured out how to make basic stone tools", "color":"white"}")
  .setRewardItems(null)
  .setNoMaxCount()
  .build();
```

**Comment by Snownee** [comment]
Hello, here is the same issue: https://discordapp.com/channels/252384449042317313/521399054391967749/755047493984583760
