### ISSUE TITLE
New UI is too big

### ISSUE THREAD

**Issue by vizthex123** [ZengineeringTeam/ResearchTable#47]
* Minecraft Version: 1.12.2
 * Mod Version: 1.0.0

I do love the new UI's design, but it takes up way too much of the screen for my liking. I even tried to reduce the UI size in the mod config and that didn't help.

Plus, NEI's "options" button overlaps and that makes it hard to use things further down.

I use auto GUI size (everything else is too small and I can't see what I'm doing), so maybe that's the problem?

Picture of the issue attached:
![image](https://user-images.githubusercontent.com/31721920/102003247-76418d80-3cca-11eb-9bcd-ac8b2be3711d.png)

**Comment by Snownee** [comment]
Preventing NEI overlay from rendering seems to be impossible. I have no idea about how to fix it
