### ISSUE TITLE
Suggestion "setRequiredResearch"

### ISSUE THREAD

**Issue by Frinn38** [ZengineeringTeam/ResearchTable#5]
Well the method "setRequiredStage" work very well but as gamestage only support lowercase without spaces, I would prefer to have for example a "setRequiredResearch(String researchID)"  to have the required research title showing in the research table instead of the stage required (because it might be confusing for players as the stage and research names are not always the same).

Thanks for reading, your mod is great and I hope you will continue to work on =D

**Comment by 3TUSK** [comment]
Hey if you look at #4 you will realized that yours is duplicated of #4 :p

**Comment by Snownee** [comment]
Added in 0.4.3

**Comment by Frinn38** [comment]
Oh sorry, I'll remember to check the other issues next time x)
Anyway thanks for the fast reply =D
