### ISSUE TITLE
[Suggestion] Add a command to reset research for all players

### ISSUE THREAD

**Issue by vizthex123** [ZengineeringTeam/ResearchTable#50]
* Minecraft Version: 1.12.2
 * Mod Version: 1.0.1

On my server, we had to restart due to a corrupted world. I deleted the game save, but the mod won't reset the progress.

I noticed too there doesn't seem to be a command to fix it, so could you add one?

Like `/researchtable reset @a` or something.

**Comment by Snownee** [comment]
should be `/researchtable @a all 0` i guess
