### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Dan4oby** [ZengineeringTeam/ResearchTable#55]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

last

### Modloader version

last

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

It would be great to add possibility to lock other technology(game stage). I need this feature for my smp modpack to allow people choose path of progression.
Also what about civ-like tech tree? It would be very visually. You can find mod From the Ground Up, which did something similar to it.

**Comment by Snownee** [comment]
This project is feature-completed. You could use FTB Quests.
