### ISSUE TITLE
请求：暂不可进行研究的任务，以及研究次数耗尽的任务进行隐藏

### ISSUE THREAD

**Issue by YiChenCraft** [ZengineeringTeam/ResearchTable#8]
理由：
        在游戏早期，并不想一次性显示全部的研究，这会缺乏惊喜。随着研究的进行，后续研究陆续解开的感觉会更棒。
        而一些已经结束了的研究如果依旧在GUI界面上显示会非常的碍事。
        如果能够将目前不可进行的研究以及超过固定的可研究次数的任务进行隐藏，会带来更清爽的体验。
       这是个非常棒的模组，希望能变得更好（为什么变得像是机翻的文本？）。

**Comment by Snownee** [comment]
已经支持了，看配置文件。
