### ISSUE TITLE
Suggestion : Hide items that are staged in list

### ISSUE THREAD

**Issue by DraxxisGH** [ZengineeringTeam/ResearchTable#9]
For example, if I had Stone conveyors and Iron motor sets staged, they still show up as their named things inside of the table instead of Unfamiliar Item. It's no huge deal.

**Comment by Snownee** [comment]
Do you mean the compatibility with ItemStages?

**Comment by DraxxisGH** [comment]
Sorry, should have specified, yes.

**Comment by Snownee** [comment]
Done.

https://minecraft.curseforge.com/projects/research-table/files/2708998
